title: "JAVIN GRAPHICS"
description: "Professional Photo Studio Website - Photography, Editing & Creative Shoots"
keywords: "Photo Studio, Photography, Editing, Portfolio, Wedding Shoot, Model Photography"
author: "Javin Graphics Team"
favicon: "/img/favicon.ico"

# _config.yml
contact:
  title: "Contact Us"
  subtitle: "If You Have Any Query, Please Contact Us"
  description: "You can reach us via the form below or directly through our email/phone."
  map: "https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d3556.8754090499583!2d76.16478699999999!3d26.939163999999995!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zMjbCsDU2JzIxLjAiTiA3NsKwMDknNTMuMiJF!5e0!3m2!1sen!2sin!4v1758941562692!5m2!1sen!2sin" # width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
  address: "Bassi Jaipur, Rajasthan"
  telegram_id: 6150091802
  phone: "+91 7062625420"
  email: "info@mrsingodiya.me"
  social:
    - icon: "fab fa-twitter"
      url: "#"
    - icon: "fab fa-facebook-f"
      url: "#"
    - icon: "fab fa-linkedin-in"
      url: "#"
    - icon: "fab fa-instagram"
      url: "#"
images: 
   hero_1: "/img/hero-1.jpg"
   hero_2: "/img/hero-2.jpg"
   

hero:
  subtitle: "Welcome To Javin Graphics"
  title: "Wedding And Portrait Studio Based in New York"
  description: "Tempor erat elitr rebum at clita..."
  button_text: "Explore More"
  button_link: "#"
  video_url: "https://www.youtube.com/embed/eDV_qiXRgr8"
  images:
    left:
      - src: "img/hero-1.jpg"
        width: "100"
        mb: true
      - src: "img/hero-3.jpg"
        width: "50"
        mb: false
    right:
      - src: "img/hero-4.jpg"
        width: "50"
        mb: true
      - src: "img/hero-2.jpg"
        width: "100"
        mb: false

plugins:
  - jekyll-redirect-from


facts:
  subtitle: "Why Choose Us!"
  title: "The Leading Photo Studio In The Country"
  items:
    - number: 35
      heading: "Award Winning"
      description: "Aliqu diam amet diam et eos..."
      delay: "0.1s"
      pt: true
    - number: 9
      heading: "Years Experience"
      description: "Aliqu diam amet diam et eos..."
      delay: "0.3s"
    - number: 2000+
      heading: "Happy Clients"
      description: "Aliqu diam amet diam et eos..."
      delay: "0.5s"
      pt: true

services:
  subtitle: "Our Services"
  title: "We Provide Best Professional Services"
  items:
    - name: "Weddings"
      img: "img/service-1.jpg"
      link: "#"
      delay: "0.1s"
    - name: "Portraits"
      img: "img/service-2.jpg"
      link: "#"
      delay: "0.3s"
      pt: true
    - name: "Fashion"
      img: "img/service-3.jpg"
      link: "#"
      delay: "0.5s"
    - name: "Editorial"
      img: "img/service-4.jpg"
      link: "#"
      delay: "0.7s"
      pt: true
footer:
  description: |
Your trusted partner for premium graphic design and printing solutions.  
We specialize in transforming your ideas into captivating visuals that not only reflect your brand identity but also leave a lasting impression. From innovative graphic design to high-quality printing, our team is dedicated to delivering professional, customized solutions that elevate your business presence. Whether you need branding, marketing materials, or promotional content, we ensure every detail is crafted with precision, creativity, and excellence to meet your unique business needs.
  quick_links:
    - name: "About Us"
      url: "/about/"
    - name: "Contact Us"
      url: "/contact/"
    - name: "Our Services"
      url: "/service/"
    - name: "Terms & Condition"
      url: "/terms/"
    - name: "Support"
      url: "/support/"

  popular_links:
    - name: "About Us"
      url: "/about/"
    - name: "Contact Us"
      url: "/contact/"
    - name: "Our Services"
      url: "/service/"
    - name: "Terms & Condition"
      url: "/terms/"
    - name: "Support"
      url: "/support/"

  copyright: "JAVIN GRAPHICS"
  credit:
    designer: "MR. SINGODIYA"
    designer_url: "https://www.mrsingodiya.me"
    distributor: "SINGODIYA TECH"
    distributor_url: "https://www.singodiya.tech"
navbar:
  left:
    - name: "Home"
      url: "/"
    - name: "About"
      url: "/about/"
    - name: "Services"
      url: "/service/"
  right:
    - name: "Projects"
      url: "/project/"
    - name: "Pages"
      dropdown:
        - name: "Features"
          url: "/feature/"
        - name: "Our Team"
          url: "/team/"
        - name: "Testimonial"
          url: "/testimonial/"
    - name: "Contact"
      url: "/contact/"

#home-about
about:
  subtitle: "About Us"
  title: "We Are Creative And Professional Photographer"
  description:
    - "Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet"
    - "Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet"
  images:
    - src: "/img/about-1.jpg"
      position: "top"
    - src: "/img/about-2.jpg"
      position: "bottom"
  features:
    - "Quality Products"
    - "Custom Products"
    - "Online Order"
    - "Home Delivery"
  button:
    text: "Read More"
    link: "/about"
